[package]
name = "crossbow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^3.0"
tokio = { version = "^1", features = ["full"] }
chrono = { version = "^0.4" , features = ["serde"] }
arrow2 = { version = "^0.9"}
serde = { version = "^1.0", features = ["derive"] }