[package]
name = "commander"
version = "0.1.0"
authors = ["Sean Toner <placeoftheway@gmail.com>"]
edition = "2021"

[features]
sync = []
async = ["tokio"]

[dependencies]
log = "0.4"
tokio = { version = "1", features = ["full"], optional = true} 
anyhow = "1"