all:
  children:
    rpi4:
      hosts:
        rpi4_master:
          ansible_host: 192.168.1.134
        rpi4_worker1:
          ansible_host: 192.168.1.148
        rpi4_worker2:
          ansible_host: 192.168.1.101
        rpi4_worker3:
          ansible_host: 192.168.1.190
      vars:
        ansible_user: ubuntu
    master:
      hosts:
        rpi4_master:
          ansible_host: 192.168.1.134
      vars:
        ansible_user: ubuntu
    workers:
      hosts:
        rpi4_worker1:
          ansible_host: 192.168.1.148
        rpi4_worker2:
          ansible_host: 192.168.1.101
        rpi4_worker3:
          ansible_host: 192.168.1.190
      vars:
        ansible_user: ubuntu